### ISSUE TITLE
Bus et Noctilien

### ISSUE THREAD

**Issue by vptcnt** [clementoriol/MetroDNA#8]
Bonjour

D'abord merci pour cette collection de sigles RATP :-)

Serait-il possible d'y rajouter les logos du B et du Noctilien ?

http://www.ratp.fr/fr/upload/docs/image/png/2013-01/picto_bus_noctilien.png
http://www.ratp.fr/fr/upload/docs/image/jpeg/2011-03/pa_picto_reseau_noctilien_fond_gris.jpg

Merci

**Comment by guillaume-algis** [comment]
@vptcnt J'ai ajouté les symboles de bus et noctilien sur ma branche [`bus`](https://github.com/guillaume-algis/MetroDNA/tree/bus).

Je n'ouvre pas de PR pour le moment puisque `bus` se base sur `optimizations`, donc tant que #9 n'est pas mergé cela va poser des soucis.

**Comment by clementoriol** [comment]
@guillaume-algis Super les symboles supplémentaires. La versions rounded du noctilien passe vraiment bien :+1: N'hésite pas à PR

**Comment by DjebbZ** [comment]
Up ?

**Comment by guillaume-algis** [comment]
@DjebbZ pourquoi "up" ? Mes PR ont été mergées (https://github.com/clementoriol/MetroDNA/pulls?q=is%3Apr+bus+is%3Aclosed)

**Comment by DjebbZ** [comment]
Oups, j'ai pas regardé le code je viens juste d'utiliser l'outil en ligne pour générer un CSS custom. Comme il ne proposait pas les bus j'ai cru que c'était pas mergé.
